<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>assets\pdfbookmarks.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="assets\left-arrow.png" />
    <None Remove="left-arrow.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="assets\left-arrow.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="assets\pdfbookmarks.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3485.44" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="left-arrow.png" />
  </ItemGroup>

  <ItemGroup>
    <None Update="helpMenu\BookmarksHelp.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="helpMenu\OpenFileHelp.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="helpMenu\SettingsHelp.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
